### ISSUE TITLE
Add noscript option on documentation

### ISSUE THREAD

**Issue by MFCo** [FormidableLabs/react-progressive-image#10]
I've been using this in some projects at work, and we always finish doing something like this:

```javascript
      <ProgressiveImage
        src="/assets/responsive/banners/example.jpg"
        placeholder="/assets/responsive-small/banners/example.jpg">
        {(src, loading) => (
          <div className="responsive-parent">
            <img className="responsive-banner" style={transitionStyle(loading)} src={src} alt="Example image" />
            <noscript>
              <img
                className="responsive-banner responsive-banner--no-script"
                src="/assets/responsive/banners/example.jpg"
                alt="Home image"
              />
            </noscript>
          </div>
        )}
      </ProgressiveImage>
```

I did it just in case JS is disabled on client side (we have SSR so is intended to work without JS), I think it would be cool to new users to know that, something like this could be added on documentation just to let them know that they should take care of this cases.

**Comment by brybrophy** [comment]
@boygirl Is this still something we want to document in the readme? If so I will add it today. If not, we an probably close this one.

**Comment by boygirl** [comment]
@brybrophy If you think it's useful, please do add it.

**Comment by MFCo** [comment]
Oh! I'm happy to see this added to documentation, I'm still using the package, I even wrote a little bit about it like a year ago in my last company :smile: 

[](http://www.startupboost.io/posts/progressive-images-react-performance-ux)

Sorry for reopening :eyes:

**Comment by scarletks1214** [comment]
Hi.
I am a great fan of this package.
I am afraid I can't get any docs or tutorial that describes onError props.
Would you please explain in detail about it?
Thanks.

**Comment by MFCo** [comment]
@scarletks1214 you can check the code. `OnError` is just a function that receive as parameter the `errorEvent` so you can handle it externally. If you don't pass anything it just go as `void` by default
