### ISSUE TITLE
component for placeholder

### ISSUE THREAD

**Issue by devinholloway** [FormidableLabs/react-progressive-image#18]
What if I don't want to render an image for the placeholder, and rather, a component. Is that possible?

**Comment by devinholloway** [comment]
actually, I figured it out. I would be something like this:

`	<ProgressiveImage src={source} placeholder=''>
		{(src, loading) => (
			loading
				? <span className="icon"><i className="fas fa-home"/></span>
				: <figure className="image"><img src={source} alt=""/></figure>
		)}
	</ProgressiveImage>`

**Comment by brybrophy** [comment]
I think we could add a prop to make this process more simple. I also think it would be nice to be able to pass in a hex color and have that rendered until the image loads, similar to the way google images does it.

**Comment by brybrophy** [comment]
That’s what I thought. Just wanted to make sure I understood the issue. 

Thanks for closing.
