### ISSUE TITLE
[Request] Adding blur and fade animations akin to Medium's progressive image loading technique

### ISSUE THREAD

**Issue by ConAntonakos** [FormidableLabs/react-progressive-image#2]
I was trying to write a component similar to what is being done here before I stumbled on this.

But I'd like to take it one step further and achieve something like this where you add a few animations to create the effect that Medium employs: https://jmperezperez.com/medium-image-progressive-loading-placeholder/

What are your thoughts?

**Comment by wcandillon** [comment]
@ConAntonakos I also build a similar component before stumbling on this package: https://github.com/wcandillon/react-progressive-image-loading

I think the blur and face animation can easily be added as a wrapper on top of this component.

**Comment by wcandillon** [comment]
@ConAntonakos this is how I implemented medium progressive image loading with this component:

```jsx
const getStyle = (src: string) => {
    const preview = src.indexOf("-preview") !== -1;
    return {
        backgroundImage: `url(${src})`,
        filter: `blur(${preview ? "10px" : "0"})`,
        transition: "filter 400ms ease"
    };
};

// ...
<ProgressiveImage placeholder={tinyPreview} src={preview}>
{(src: string) => <div style={getStyle(src)} />}
</ProgressiveImage>
```

The preview is infered from the source name, it would be great if this component would give a boolean in the callback to findout if this is the final image or not.

**Comment by wcandillon** [comment]
Also it would be useful to first load the preview and then the second image. Doesn't seem to be the case the moment.

**Comment by evenchange4** [comment]
LOL! I worked for almost the same problem today 😅 with [react-progressive-bg-image](https://github.com/evenchange4/react-progressive-bg-image).
But, It is based on another styling library `styled-compoents` to decorate the component which targets to **background-image**.

**Comment by aweary** [comment]
You can now use a new, second argument to the render callback to determine if the primary image is still loading https://github.com/FormidableLabs/react-progressive-image/pull/6
