### ISSUE TITLE
Causes getServerSideProps to run twice for a NextJS dynamic route

### ISSUE THREAD

**Issue by johnruane** [FormidableLabs/react-progressive-image#34]
I am using this component in my NextJS project. We have a Dynamic route set up which takes the query parameters and passes them to a page which contains an Image using this package.

When react-progressive-image is used we are seeing that the getServerSideProps function within our Dynamic route is called twice (should only be called once on the server). The second time it is called the query params are undefined.

Have created a reduced test case repo: https://github.com/johnruane/dynamic-route-test

When using a static named route getServerSidePorps is only called once.

Can anyone shed light on why a serverside function would be called twice? If it was a clientside call that may be more understandable as the page may rerender. This could be an issue with NextJS but I wanted to start here first.

**Comment by sanishkr** [comment]
It doesn't look like your issue has anything to do with this library.
After commenting it, you still get 2 logs, one undefined in dynamic routing case.
Seems, it has to do with the way you are implementing routing.

[codesandbox](https://codesandbox.io/s/new-cherry-yctb1?file=/pages/dynamic/%5B...search%5D.js)

**Comment by djleonskennedy** [comment]
@johnruane Have same issue, move some logic to client because of that

**Comment by djleonskennedy** [comment]
@johnruane https://github.com/vercel/next.js/issues/27305 here is an answer on your issue

**Comment by johnruane** [comment]
@djleonskennedy This has resolved my issue. Thanks
