### ISSUE TITLE
How to have the container div height and width calculated automatically based on image sizes before mounting the component?

### ISSUE THREAD

**Issue by Superpencil** [FormidableLabs/react-progressive-image#5]
Auto set height and width somehow while preventing reflow on load?

**Comment by mirik999** [comment]
good question , i need some hack too.

**Comment by Superpencil** [comment]
It's impossible to get height and width of an image before it is at least partially loaded, the best thing to do is hard-code an aspect ratio in your css using `padding-top: 50%` as the `%` is based on the width of the image.

**Comment by brybrophy** [comment]
That’s what I thought. Just wanted to make sure I understood the issue. 

Thanks for closing.
